specfile_path: packaging/goose-proxy.spec
upstream_package_name: goose-proxy
downstream_package_name: goose-proxy
upstream_project_url: https://github.com/rhel-lightspeed/goose-proxy

srpm_build_deps: []

jobs:
  # Build RPMs for each pull request
  - job: copr_build
    trigger: pull_request
    owner: "@rhel-lightspeed"
    project: goose-proxy
    targets:
      - fedora-43-x86_64
      - fedora-43-aarch64
      - fedora-43-ppc64le
      - fedora-43-s390x
      - fedora-44-x86_64
      - fedora-44-aarch64
      - fedora-44-ppc64le
      - fedora-44-s390x
      - fedora-rawhide-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
    actions:
      # do not get the version from a tag (git describe) but from the spec file
      get-current-version:
        - grep -oP '^Version:\s+\K\S+' packaging/goose-proxy.spec

  # Build RPMs for main branch
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@rhel-lightspeed"
    project: goose-proxy
    targets:
      - fedora-43-x86_64
      - fedora-43-aarch64
      - fedora-43-ppc64le
      - fedora-43-s390x
      - fedora-44-x86_64
      - fedora-44-aarch64
      - fedora-44-ppc64le
      - fedora-44-s390x
      - fedora-rawhide-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-ppc64le
      - fedora-rawhide-s390x
    actions:
      # bump spec so we get release starting with 2 and hence all the default branch builds will
      # have higher NVR than all the PR builds
      post-upstream-clone:
        - rpmdev-bumpspec --comment='latest upstream build' ./packaging/goose-proxy.spec
      # do not get the version from a tag (git describe) but from the spec file
      get-current-version:
        - grep -oP '^Version:\s+\K\S+' packaging/goose-proxy.spec
