from typing import Annotated, Any, Literal, Optional, Union

from pydantic import BaseModel, Field


class TextContentPart(BaseModel):
    """A text content block in a multipart message."""

    type: Literal["text"] = "text"
    text: str


class ImageUrlDetail(BaseModel):
    """Image URL reference within an image content block."""

    url: str


class ImageUrlContentPart(BaseModel):
    """An image_url content block in a multipart message."""

    type: Literal["image_url"] = "image_url"
    image_url: ImageUrlDetail


ContentPart = Annotated[
    Union[TextContentPart, ImageUrlContentPart],
    Field(discriminator="type"),
]


class ModelInfo(BaseModel):
    """Information about a single model, in OpenAI-compatible format."""

    id: str
    object: str = "model"
    created: int = 0
    owned_by: str = "rhel-lightspeed"


class ModelsResponse(BaseModel):
    """Response containing list of available models."""

    object: str = "list"
    data: list[ModelInfo]


class Function(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format.
    """

    name: str
    """The name of the function to call."""


class ChatCompletionMessageToolCall(BaseModel):
    id: str
    """The ID of the tool call."""

    function: Function
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class ToolFunction(BaseModel):
    """Function definition for a tool."""

    name: str
    description: Optional[str] = None
    parameters: Optional[dict[str, Any]] = None


class Tool(BaseModel):
    """Tool definition for function calling."""

    type: Literal["function"] = "function"
    function: ToolFunction


class ChatMessage(BaseModel):
    """A single message in a chat conversation."""

    role: Literal["system", "user", "assistant", "tool"] = "user"
    content: Optional[Union[str, list[ContentPart]]] = None
    tool_calls: Optional[list[ChatCompletionMessageToolCall]] = None
    tool_call_id: Optional[str] = None
    name: Optional[str] = None


class ChatCompletionRequest(BaseModel):
    """OpenAI-compatible chat completion request."""

    model: str = Field(..., description="Model to use for completion")
    messages: list[ChatMessage] = Field(
        ..., description="List of messages in the conversation"
    )
    stream: bool = Field(default=False, description="Whether to stream responses")
    tools: Optional[list[Tool]] = Field(
        default=None, description="List of tools the model can call"
    )
    tool_choice: Optional[Union[str, dict[str, Any]]] = Field(
        default=None, description="Controls which tool is called"
    )
    temperature: Optional[float] = Field(
        default=None, description="Sampling temperature"
    )
    max_tokens: Optional[int] = Field(
        default=None, description="Maximum number of tokens to generate"
    )
    stream_options: Optional[dict[str, Any]] = Field(
        default=None, description="Options for streaming responses"
    )


# --- Chat Completion response models ---


class CompletionUsage(BaseModel):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class ChatCompletionResponseMessage(BaseModel):
    """Assistant message in a chat completion response."""

    role: str = "assistant"
    content: Optional[str] = None
    tool_calls: Optional[list[ChatCompletionMessageToolCall]] = None


class Choice(BaseModel):
    index: int
    message: ChatCompletionResponseMessage
    finish_reason: str


class ChatCompletion(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: list[Choice]
    usage: Optional[CompletionUsage] = None
