name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sanity:
    name: Sanity - ${{ matrix.test.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Lint
            step_name: Run lint check
            command: ruff check --diff src/ tests/

          - name: Format
            step_name: Run format check
            command: ruff format --diff src/ tests/

          - name: Type
            step_name: Check types
            command: ty check src/

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version-file: pyproject.toml
          allow-prereleases: true

      - name: Install dependencies
        run: uv sync --locked --group dev

      - name: ${{ matrix.test.step_name }}
        run: uv run --locked ${{ matrix.test.command }}

  test:
    name: Unit - ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          prune-cache: false

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install dependencies
        run: uv sync --locked --group dev

      - name: Run tests
        run: uv run --locked pytest
