name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sanity:
    name: Sanity - ${{ matrix.test.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          - name: Lint
            step_name: Run lint check
            command: ruff check --diff src/ tests/

          - name: Format
            step_name: Run format check
            command: ruff format --diff src/ tests/

          - name: Type
            step_name: Check types
            command: ty check src/

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
          allow-prereleases: true

      - name: Install dependencies
        run: uv sync --locked --group dev

      - name: ${{ matrix.test.step_name }}
        run: uv run --locked ${{ matrix.test.command }}

  test:
    name: Unit - ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install dependencies
        run: uv sync --locked --group dev

      - name: Run tests
        run: uv run --locked pytest
