name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  sanity:
    name: Sanity - ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.9"  # RHEL 9.8/9.9
          - "3.10"
          - "3.11"
          - "3.12" # RHEL 10.3/10.4
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          prune-cache: false
      - run: make setup

      - parallel:
          - name: Lint
            run: make lint

          - name: Format
            run: make format

          - name: Typecheck
            run: make type

          - name: Test
            run: make test
